site_name: TorQ Amazon FinSpace Starter Pack
nav:
    - Home: index.md
    - Getting Started: gettingstarted.md
    - Architecture: architecture.md
    - Deploy Using Terraform: terraformdeloyment.md

repo_name: 'GitHub'
repo_url: 'https://github.com/DataIntellectTech/TorQ-Amazon-FinSpace-Starter-Pack'

theme:
  favicon: graphics/favicon.ico
  name: material
  logo: graphics/DataIntellect-header-logo.jpg
  features:
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_name: GitHub
repo_url: https://github.com/DataIntellectTech/TorQ

extra:
   social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/DataIntellectTech
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/data_intellect
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/data-intellect-challenge-accepted
   analytics:
      provider: google
      property: UA-51911331-4
plugins:
  - search

copyright: Copyright &copy 2023 Data Intellect Limited.  Kx &reg and kdb+ are registered trademarks of Kx Systems Inc.